version: '3.3'
services:
  web:
    image: enmai1988/techstarter:latest
    depends_on:
      - redis
      - postgres
    ports:
      - 8000:3000
    links:
      - postgres
      - redis

  redis:
    image: redis:4.0.1

  postgres:
    image: postgres:9.6.3
    ports:
      - 5432:5432
    environment:
     POSTGRES_USER: user
     POSTGRES_PASSWORD: mimo
     POSTGRES_DB: techstarter
